#========================
# Project Information
#========================

project.name=Utajir Creator Automation Framework

company=Utajir

tester=Mohamed Alshahat

environment=QA

browser=Chrome

device=Windows 11

base.url=https://main-creator.utajir.com

#========================
# Report
#========================

report.folder=Reports

report.theme=dark

report.screenshot.on.pass=false

report.screenshot.on.fail=true

#========================
# Execution
#========================

execution.retry=0

execution.timeout=30